import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import styles from "./page.module.css"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import Theme from '@/utils/theme'
import { createClient } from '@/utils/supabase/server'
import { cookies } from 'next/headers'
import { CssBaseline, Paper, Toolbar } from '@mui/material'
import Header from '@/components/Header'
import Main from '@/components/Main'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }
export const metadata: Metadata = {
  title: {
    template: '%s | PokéTracker',
    default: 'PokéTracker',
  },
  icons: {
    // icon: '/pokeball.svg'
    icon: '/pokeball-dark.png'
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies()
  const supabase = createClient(cookieStore)

  const { data: { session } } = await supabase.auth.getSession()

  return (
    <Theme>
      <html lang="en">
        <body className={inter.className}>
          <AppRouterCacheProvider>
            <Header session={session} />
            {children}
            <Footer />
          </AppRouterCacheProvider>
        </body>
      </html>
    </Theme>
  )
}
