import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import './globals.css'
import styles from "./page.module.css"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import Theme from '@/utils/theme'
import { createClient } from '@/utils/supabase/server'
import { cookies } from 'next/headers'
import { CssBaseline, Toolbar } from '@mui/material'
import Main from '@/components/Main'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies()
  const supabase = createClient(cookieStore)

  const {
    data: { session },
  } = await supabase.auth.getSession()

  return (
    <Theme>
      <html lang="en">
        <body className={inter.className}>
          <AppRouterCacheProvider>
            <Header session={session} />
            {children}
            <footer></footer>
          </AppRouterCacheProvider>
        </body>
      </html>
    </Theme>
  )
}
